# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='web_mail',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
