# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
