# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20170111_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.CharField(blank=True, help_text='Write a bio that reflects your interests.', max_length=300, null=True, verbose_name='Bio'),
        ),
    ]
