# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_student_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='homepage_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL of Homepage'),
        ),
    ]
