from __future__ import unicode_literals

from django.conf.urls import url

from . import views_faculty, views_student

urlpatterns = [
    url(r'^faculty/projects/create/$', views_faculty.ProjectCreate.as_view(),
        name='fac-project-create',),
    url(r'^faculty/projects/list/(?P<page>\d+)/$', 
        views_faculty.ProjectList.as_view(), name='fac-project-list'),
    url(r'^faculty/projects/detail/(?P<pk>\d+)/$',
        views_faculty.ProjectDetail.as_view(), name='fac-project-detail'),
    url(r'^faculty/projects/update/(?P<pk>\d+)/$',
        views_faculty.ProjectUpdate.as_view(), name='fac-project-update'),
    url(r'^faculty/projects/search/$',
        views_faculty.SearchProject.as_view(), name='fac-project-search'),
    url(r'^faculty/project/search/detail/(?P<pk>\d+)/$',
        views_faculty.ProjectSearchDetail.as_view(),
        name='fac-project-search-detail'),
    url(r'faculty/projects/list/csv$', views_faculty.ProjectListCSV.as_view(),
        name='fac-project-list-csv'),
    url(r'^faculty/tag/list/(?P<page>\d+)/$', views_faculty.SkillList.as_view(),
        name='fac-skill-list'),
    url(r'^faculty/tag/create/$', views_faculty.SkillCreate.as_view(),
        name='fac-skill-create'),
    url(r'^faculty/tag/(?P<pk>\d+)/detail/$',
        views_faculty.SkillDetail.as_view(), name='fac-skill-detail'),
    url(r'^faculty/tag/(?P<pk>\d+)/update/$',
        views_faculty.SkillUpdate.as_view(), name='fac-skill-update'),
    url(r'faculty/project-stud-rel/(?P<relid>\d+)/update/(?P<action>\d+)/$',
        views_faculty.ProjectStudRelUpdate.as_view(),
        name='fac-proj-stud-rel-update'),

    url(r'^student/projects/list/(?P<page>\d+)/$',
        views_student.ProjectList.as_view(), name='stud-project-list'),
    url(r'^student/projects/list/tag/(?P<pk>\d+)/$',
        views_student.ProjectListBySkill.as_view(),
        name='stud-project-list-by-skill'),
    url(r'^student/projects/detail/(?P<pk>\d+)/$',
        views_student.ProjectDetail.as_view(), name='stud-project-detail'),
    url(r'^student/projects/apply/(?P<pk>\d+)/$',
        views_student.ProjectStudRelCreate.as_view(),
        name='stud-project_stud_rel-create'),
    url(r'student/project-rel/list/',
        views_student.ProjectStudentRelationList.as_view(),
        name='stud-project_stud_rel-list'),
    url(r'^student/projects/deapply/(?P<pk>\d+)/$',
        views_student.ProjectStudRelDelete.as_view(),
        name='stud-project_stud_rel-delete'),
    url(r'^student/projects/search/',
        views_student.SearchProject.as_view(), name='stud-project-search'),
]
