# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, to='projects.Skill'),
        ),
    ]
