# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-05 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectstudentrelation',
            old_name='is_completed',
            new_name='abandon_status',
        ),
        migrations.RenameField(
            model_name='projectstudentrelation',
            old_name='is_shortlisted',
            new_name='completion_status',
        ),
        migrations.AddField(
            model_name='projectstudentrelation',
            name='abandon_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstudentrelation',
            name='shortlist_status',
            field=models.NullBooleanField(default=None),
        ),
    ]
