# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20161029_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deletion_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
