# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('projects', '0004_auto_20161030_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStudentRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='projectstudentrelation',
            unique_together=set([('project', 'student')]),
        ),
    ]
