# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20161030_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hours_per_week',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=3, verbose_name='Hours Per Week'),
        ),
    ]
