# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_hours_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='closing_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectstudentrelation',
            name='completion_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstudentrelation',
            name='is_completed',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='projectstudentrelation',
            name='is_shortlisted',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='projectstudentrelation',
            name='shortlist_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
