# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20161102_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='project',
            name='requirements',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Other Requirements'),
        ),
    ]
