# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20161102_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Tentative End Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Tentative Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='closing_datetime',
            field=models.DateTimeField(blank=True, help_text='Applications will close after this date.', null=True, verbose_name='Closing Date'),
        ),
    ]
