# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('projects', '0009_auto_20161102_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='applicants',
            field=models.ManyToManyField(through='projects.ProjectStudentRelation', to='profiles.Student'),
        ),
    ]
