# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstudentrelation',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
