# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectstudentrelation_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
